apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpuup-deployment
  labels:
    app: cpuup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpuup
  template:
    metadata:
      labels:
        app: cpuup
    spec:
      containers:
      - name: cpuup
        image: docker-registry-default.apps.paosin.local/autoscaler/cpuup:v1.3
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-08-03T04:27:50Z","reason":"ReadyForNewScale","message":"the
      last scale time was sufficiently old as to warrant a new scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2018-08-03T04:27:50Z","reason":"ValidMetricFound","message":"the
      HPA was able to succesfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2018-08-03T04:28:20Z","reason":"TooFewReplicas","message":"the
      desired replica count is more than the maximum replica count"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
  creationTimestamp: 2018-08-03T04:27:20Z
  labels:
    app: cpuup
  name: cpuup-deployment
spec:
  maxReplicas: 1
  minReplicas: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: cpuup-deployment
  targetCPUUtilizationPercentage: 50

---
kind: Service
apiVersion: v1
metadata:
  name: cpuup-service
spec:
  selector:
    app: cpuup
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cpuup-service
  namespace: autoscaler
spec:
  host: cpuup-service-autoscaler.apps.paosin.local
  to:
    kind: Service
    name: cpuup-service
    weight: 100
  wildcardPolicy: None
